# Generated by Django 4.1.3 on 2023-11-02 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Orders",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=5000)),
                ("customer_id", models.CharField(max_length=5000)),
                ("customer_name", models.CharField(max_length=5000)),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_phone", models.CharField(max_length=20)),
                ("order_date", models.DateField()),
                ("order_status", models.CharField(max_length=5000)),
                (
                    "subtotal_inc_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "subtotal_ex_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("tax_total", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "shipping_cost_inc_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "shipping_cost_ex_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("ship_method", models.CharField(max_length=5000)),
                (
                    "handling_cost_inc_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "handling_cost_ex_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "store_credit_redeemed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "gift_certificate_amount_redeemed",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("gift_certificate_code", models.CharField(max_length=5000)),
                ("gift_certificate_expiration_date", models.DateField()),
                ("coupon_details", models.TextField()),
                (
                    "order_total_inc_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "order_total_ex_tax",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("payment_method", models.CharField(max_length=5000)),
                ("total_quantity", models.IntegerField()),
                ("total_shipped", models.IntegerField()),
                ("date_shipped", models.DateField()),
                ("order_currency_code", models.CharField(max_length=3)),
                ("exchange_rate", models.DecimalField(decimal_places=6, max_digits=10)),
                ("order_notes", models.TextField()),
                ("customer_message", models.TextField()),
                ("billing_first_name", models.CharField(max_length=5000)),
                ("billing_last_name", models.CharField(max_length=5000)),
                ("billing_company", models.CharField(max_length=5000)),
                ("billing_street_1", models.CharField(max_length=5000)),
                ("billing_street_2", models.CharField(max_length=5000)),
                ("billing_suburb", models.CharField(max_length=5000)),
                ("billing_state", models.CharField(max_length=5000)),
                ("billing_zip", models.CharField(max_length=20)),
                ("billing_country", models.CharField(max_length=5000)),
                ("billing_phone", models.CharField(max_length=20)),
                ("billing_email", models.EmailField(max_length=254)),
                ("billing_tax_id", models.CharField(max_length=5000)),
                ("shipping_first_name", models.CharField(max_length=5000)),
                ("shipping_last_name", models.CharField(max_length=5000)),
                ("shipping_company", models.CharField(max_length=5000)),
                ("shipping_street_1", models.CharField(max_length=5000)),
                ("shipping_street_2", models.CharField(max_length=5000)),
                ("shipping_suburb", models.CharField(max_length=5000)),
                ("shipping_state", models.CharField(max_length=5000)),
                ("shipping_zip", models.CharField(max_length=20)),
                ("shipping_country", models.CharField(max_length=5000)),
                ("shipping_phone", models.CharField(max_length=20)),
                ("shipping_email", models.EmailField(max_length=254)),
                ("shipping_tax_id", models.CharField(max_length=5000)),
                ("product_details", models.TextField()),
                ("refund_amount", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
