# Generated by Django 4.1.3 on 2023-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_orders_billing_company_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orders",
            name="billing_phone",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="billing_zip",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="order_currency_code",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="shipping_phone",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name="orders",
            name="shipping_zip",
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
