# Generated by Django 4.1.3 on 2023-11-08 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0004_orders_company_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "company_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
        ),
    ]
